### ISSUE TITLE
Implementar secção de benefícios

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/site#5]
O site atual tem uma grelha de blocos de benefícios que a comunidade proporciona que deverá ser re-implementada neste repositório.

A implementação atual está também esta já preparada para mobile, comportamento que deve ser mantido.

**Assets:**
![image](https://user-images.githubusercontent.com/1396475/209584450-62c0f48e-ce91-44c5-9f6c-a0adce21062d.png)

[Preview](https://devpt.co)

**Comment by rguedes** [comment]
Posso pegar nisto.

Querem algo estático ou dinâmico gerido pelo backend?

Ou preparado para ser dinâmico?

**Comment by IvoPereira** [comment]
Penso que podemos avançar com algo estático por agora @rguedes, penso que serve perfeitamente :smile:

**Comment by IvoPereira** [comment]
Closed by https://github.com/devpt-org/site/pull/8.
